params:
  run_date: "auto"

paths:
  member_transactions:
    path: "./data/tx.csv"
    sep: ";"
    format: "csv"
  member_info:
    path: "./data/members.csv"
    sep: ","
    format: "csv"
  out:
    path: "s3://bla/out/archive/year={year}/month={month}/"